# Form implementation generated from reading ui file 'fast_food_menu.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("""
QFrame {
    background-color: #f5f5f5;
    border: 1px solid #dcdcdc;
    border-radius: 12px;
}
QFrame#frmMenu {
    background-color: #ffffff;
    border: 1px solid #dcdcdc;
    border-radius: 12px;
    padding: 8px;
}
QFrame#frmCheckout {
    background-color: #ffffff;
    border: 1px solid #dcdcdc;
    border-radius: 12px;
    padding: 10px;
}
QLabel {
    color: #222;
    font: 11pt \"Segoe UI\";
}

QPushButton {
    border: none;
    border-radius: 6px;
    color: white;
    font: bold 11pt \"Segoe UI\";
}
QPushButton[objectName^=\"btnAdd\"] {
    background-color: #43a047;
}
QPushButton[objectName^=\"btnAdd\"]:hover {
    background-color: #388e3c;
}
QPushButton[objectName^=\"btnMinus\"] {
    background-color: #e53935;
}
QPushButton[objectName^=\"btnMinus\"]:hover {
    background-color: #d32f2f;
}
QPushButton#btnCheckout {
   background-color: #ffa000;
    border-radius: 10px;
    font: bold 11pt \"Segoe UI\";
    padding: 8px 16px;
}
QPushButton#btnCheckout:hover {
    background-color: #fb8c00;
}
QLabel#lblMenuTitle {
    background-color: #ffffff;
    border: 2px solid #ffa000;
    border-radius: 16px;
    padding: 6px 20px;
    font: bold 20pt \"Segoe UI\";
    color: #333333;
}
QLabel#lblCheckoutTitle {
    background-color: #f5f5f5;
    border: 1px solid #dcdcdc;
    border-radius: 12px;
    padding: 4px 10px;
    font: bold 20pt \"Segoe UI\";
    color: #333;"
}
""")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frmTop = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmTop.setMinimumSize(QtCore.QSize(0, 80))
        self.frmTop.setStyleSheet("background-color: #f0f0f0;")
        self.frmTop.setObjectName("frmTop")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout(self.frmTop)
        self.horizontalLayout_top.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_top.setSpacing(4)
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.lblLogo = QtWidgets.QLabel(parent=self.frmTop)
        self.lblLogo.setMinimumSize(QtCore.QSize(120, 60))
        self.lblLogo.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("images/logo.jpg"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout_top.addWidget(self.lblLogo)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem)
        self.lblMenuTitle = QtWidgets.QLabel(parent=self.frmTop)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblMenuTitle.setFont(font)
        self.lblMenuTitle.setStyleSheet("""
        QLabel#MenuTitle {"
            background-color: #f5f5f5;
            border: 1px solid #dcdcdc;
            border-radius: 12px;
            padding: 4px 10px;
            font: bold 20pt \"Segoe UI\";
            color: #333;
        }
        """)
        self.lblMenuTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMenuTitle.setObjectName("lblMenuTitle")
        self.horizontalLayout_top.addWidget(self.lblMenuTitle)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem1)
        self.horizontalLayout_top.setStretch(0, 1)
        self.horizontalLayout_top.setStretch(1, 1)
        self.horizontalLayout_top.setStretch(2, 3)
        self.horizontalLayout_top.setStretch(3, 2)
        self.verticalLayout.addWidget(self.frmTop)
        self.horizontalLayout_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.frmMenu = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmMenu.setStyleSheet("""
                background-color: #ffffff;
                QLabel#lblMenuTitle {
                        background-color: #ffffff;
                        border: 2px solid #ffa000;
                        border-radius: 16px;
                        padding: 6px 20px;
                        font: bold 20pt \"Segoe UI\";"
                        color: #333333;"
                }
        """)
        self.frmMenu.setObjectName("frmMenu")
        self.gridLayout_menu = QtWidgets.QGridLayout(self.frmMenu)
        self.gridLayout_menu.setContentsMargins(-1, -1, 8, 8)
        self.gridLayout_menu.setSpacing(8)
        self.gridLayout_menu.setObjectName("gridLayout_menu")
        self.frmItem1 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem1.setObjectName("frmItem1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frmItem1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblItem1 = QtWidgets.QLabel(parent=self.frmItem1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.lblItem1.sizePolicy().hasHeightForWidth())
        self.lblItem1.setSizePolicy(sizePolicy)
        self.lblItem1.setMinimumSize(QtCore.QSize(250, 150))
        self.lblItem1.setPixmap(QtGui.QPixmap("images/ga_ran.png"))
        self.lblItem1.setScaledContents(True)
        self.lblItem1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem1.setProperty("iconSize", QtCore.QSize(110, 110))
        self.lblItem1.setObjectName("lblItem1")
        self.verticalLayout_10.addWidget(self.lblItem1)
        self.hlayout_btns1 = QtWidgets.QHBoxLayout()
        self.hlayout_btns1.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.hlayout_btns1.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns1.setSpacing(4)
        self.hlayout_btns1.setObjectName("hlayout_btns1")
        self.btnAdd1 = QtWidgets.QPushButton(parent=self.frmItem1)
        self.btnAdd1.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd1.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd1.setObjectName("btnAdd1")
        self.hlayout_btns1.addWidget(self.btnAdd1)
        self.btnMinus1 = QtWidgets.QPushButton(parent=self.frmItem1)
        self.btnMinus1.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus1.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus1.setObjectName("btnMinus1")
        self.hlayout_btns1.addWidget(self.btnMinus1)
        self.verticalLayout_10.addLayout(self.hlayout_btns1)
        self.gridLayout_menu.addWidget(self.frmItem1, 0, 0, 1, 1)
        self.frmItem2 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem2.setObjectName("frmItem2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmItem2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblItem2 = QtWidgets.QLabel(parent=self.frmItem2)
        self.lblItem2.setMinimumSize(QtCore.QSize(250, 150))
        self.lblItem2.setPixmap(QtGui.QPixmap("images/ga_chien_gion.png"))
        self.lblItem2.setScaledContents(True)
        self.lblItem2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem2.setProperty("iconSize", QtCore.QSize(110, 110))
        self.lblItem2.setObjectName("lblItem2")
        self.verticalLayout_2.addWidget(self.lblItem2)
        self.hlayout_btns2 = QtWidgets.QHBoxLayout()
        self.hlayout_btns2.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns2.setObjectName("hlayout_btns2")
        self.btnAdd2 = QtWidgets.QPushButton(parent=self.frmItem2)
        self.btnAdd2.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd2.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd2.setObjectName("btnAdd2")
        self.hlayout_btns2.addWidget(self.btnAdd2)
        self.btnMinus2 = QtWidgets.QPushButton(parent=self.frmItem2)
        self.btnMinus2.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus2.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus2.setObjectName("btnMinus2")
        self.hlayout_btns2.addWidget(self.btnMinus2)
        self.verticalLayout_2.addLayout(self.hlayout_btns2)
        self.gridLayout_menu.addWidget(self.frmItem2, 0, 1, 1, 1)
        self.frmItem3 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem3.setObjectName("frmItem3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmItem3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblItem3 = QtWidgets.QLabel(parent=self.frmItem3)
        self.lblItem3.setMinimumSize(QtCore.QSize(250, 150))
        self.lblItem3.setPixmap(QtGui.QPixmap("images/ga_cay.png"))
        self.lblItem3.setScaledContents(True)
        self.lblItem3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem3.setProperty("iconSize", QtCore.QSize(110, 110))
        self.lblItem3.setObjectName("lblItem3")
        self.verticalLayout_3.addWidget(self.lblItem3)
        self.hlayout_btns3 = QtWidgets.QHBoxLayout()
        self.hlayout_btns3.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns3.setObjectName("hlayout_btns3")
        self.btnAdd3 = QtWidgets.QPushButton(parent=self.frmItem3)
        self.btnAdd3.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd3.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd3.setObjectName("btnAdd3")
        self.hlayout_btns3.addWidget(self.btnAdd3)
        self.btnMinus3 = QtWidgets.QPushButton(parent=self.frmItem3)
        self.btnMinus3.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus3.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus3.setObjectName("btnMinus3")
        self.hlayout_btns3.addWidget(self.btnMinus3)
        self.verticalLayout_3.addLayout(self.hlayout_btns3)
        self.gridLayout_menu.addWidget(self.frmItem3, 0, 2, 1, 1)
        self.frmItem4 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem4.setObjectName("frmItem4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frmItem4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblItem4 = QtWidgets.QLabel(parent=self.frmItem4)
        self.lblItem4.setMinimumSize(QtCore.QSize(250, 150))
        self.lblItem4.setPixmap(QtGui.QPixmap("images/ga_vien.png"))
        self.lblItem4.setScaledContents(True)
        self.lblItem4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem4.setProperty("iconSize", QtCore.QSize(110, 110))
        self.lblItem4.setObjectName("lblItem4")
        self.verticalLayout_4.addWidget(self.lblItem4)
        self.hlayout_btns4 = QtWidgets.QHBoxLayout()
        self.hlayout_btns4.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns4.setObjectName("hlayout_btns4")
        self.btnAdd4 = QtWidgets.QPushButton(parent=self.frmItem4)
        self.btnAdd4.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd4.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd4.setObjectName("btnAdd4")
        self.hlayout_btns4.addWidget(self.btnAdd4)
        self.btnMinus4 = QtWidgets.QPushButton(parent=self.frmItem4)
        self.btnMinus4.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus4.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus4.setObjectName("btnMinus4")
        self.hlayout_btns4.addWidget(self.btnMinus4)
        self.verticalLayout_4.addLayout(self.hlayout_btns4)
        self.gridLayout_menu.addWidget(self.frmItem4, 1, 0, 1, 1)
        self.frmItem5 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem5.setObjectName("frmItem5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frmItem5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblItem5 = QtWidgets.QLabel(parent=self.frmItem5)
        self.lblItem5.setMinimumSize(QtCore.QSize(250, 150))
        self.lblItem5.setPixmap(QtGui.QPixmap("images/burger_ga.png"))
        self.lblItem5.setScaledContents(True)
        self.lblItem5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem5.setProperty("iconSize", QtCore.QSize(110, 110))
        self.lblItem5.setObjectName("lblItem5")
        self.verticalLayout_5.addWidget(self.lblItem5)
        self.hlayout_btns5 = QtWidgets.QHBoxLayout()
        self.hlayout_btns5.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns5.setObjectName("hlayout_btns5")
        self.btnAdd5 = QtWidgets.QPushButton(parent=self.frmItem5)
        self.btnAdd5.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd5.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd5.setObjectName("btnAdd5")
        self.hlayout_btns5.addWidget(self.btnAdd5)
        self.btnMinus5 = QtWidgets.QPushButton(parent=self.frmItem5)
        self.btnMinus5.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus5.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus5.setObjectName("btnMinus5")
        self.hlayout_btns5.addWidget(self.btnMinus5)
        self.verticalLayout_5.addLayout(self.hlayout_btns5)
        self.gridLayout_menu.addWidget(self.frmItem5, 1, 1, 1, 1)
        self.frmItem6 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem6.setObjectName("frmItem6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmItem6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblItem6 = QtWidgets.QLabel(parent=self.frmItem6)
        self.lblItem6.setMinimumSize(QtCore.QSize(250, 150))
        self.lblItem6.setPixmap(QtGui.QPixmap("images/burger_ga_special.png"))
        self.lblItem6.setScaledContents(True)
        self.lblItem6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem6.setProperty("iconSize", QtCore.QSize(110, 110))
        self.lblItem6.setObjectName("lblItem6")
        self.verticalLayout_6.addWidget(self.lblItem6)
        self.hlayout_btns6 = QtWidgets.QHBoxLayout()
        self.hlayout_btns6.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns6.setObjectName("hlayout_btns6")
        self.btnAdd6 = QtWidgets.QPushButton(parent=self.frmItem6)
        self.btnAdd6.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd6.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd6.setObjectName("btnAdd6")
        self.hlayout_btns6.addWidget(self.btnAdd6)
        self.btnMinus6 = QtWidgets.QPushButton(parent=self.frmItem6)
        self.btnMinus6.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus6.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus6.setObjectName("btnMinus6")
        self.hlayout_btns6.addWidget(self.btnMinus6)
        self.verticalLayout_6.addLayout(self.hlayout_btns6)
        self.gridLayout_menu.addWidget(self.frmItem6, 1, 2, 1, 1)
        self.frmItem7 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem7.setObjectName("frmItem7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frmItem7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblItem7 = QtWidgets.QLabel(parent=self.frmItem7)
        self.lblItem7.setMinimumSize(QtCore.QSize(220, 150))
        self.lblItem7.setPixmap(QtGui.QPixmap("images/pepsi.png"))
        self.lblItem7.setScaledContents(True)
        self.lblItem7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem7.setProperty("iconSize", QtCore.QSize(50, 70))
        self.lblItem7.setObjectName("lblItem7")
        self.verticalLayout_7.addWidget(self.lblItem7)
        self.hlayout_btns7 = QtWidgets.QHBoxLayout()
        self.hlayout_btns7.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns7.setObjectName("hlayout_btns7")
        self.btnAdd7 = QtWidgets.QPushButton(parent=self.frmItem7)
        self.btnAdd7.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd7.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd7.setObjectName("btnAdd7")
        self.hlayout_btns7.addWidget(self.btnAdd7)
        self.btnMinus7 = QtWidgets.QPushButton(parent=self.frmItem7)
        self.btnMinus7.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus7.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus7.setObjectName("btnMinus7")
        self.hlayout_btns7.addWidget(self.btnMinus7)
        self.verticalLayout_7.addLayout(self.hlayout_btns7)
        self.gridLayout_menu.addWidget(self.frmItem7, 2, 0, 1, 1)
        self.frmItem8 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem8.setObjectName("frmItem8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frmItem8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblItem8 = QtWidgets.QLabel(parent=self.frmItem8)
        self.lblItem8.setMinimumSize(QtCore.QSize(220, 150))
        self.lblItem8.setPixmap(QtGui.QPixmap("images/cocacola.png"))
        self.lblItem8.setScaledContents(True)
        self.lblItem8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem8.setProperty("iconSize", QtCore.QSize(50, 70))
        self.lblItem8.setObjectName("lblItem8")
        self.verticalLayout_8.addWidget(self.lblItem8)
        self.hlayout_btns8 = QtWidgets.QHBoxLayout()
        self.hlayout_btns8.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns8.setObjectName("hlayout_btns8")
        self.btnAdd8 = QtWidgets.QPushButton(parent=self.frmItem8)
        self.btnAdd8.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd8.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd8.setObjectName("btnAdd8")
        self.hlayout_btns8.addWidget(self.btnAdd8)
        self.btnMinus8 = QtWidgets.QPushButton(parent=self.frmItem8)
        self.btnMinus8.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus8.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus8.setObjectName("btnMinus8")
        self.hlayout_btns8.addWidget(self.btnMinus8)
        self.verticalLayout_8.addLayout(self.hlayout_btns8)
        self.gridLayout_menu.addWidget(self.frmItem8, 2, 1, 1, 1)
        self.frmItem9 = QtWidgets.QFrame(parent=self.frmMenu)
        self.frmItem9.setObjectName("frmItem9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frmItem9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblItem9 = QtWidgets.QLabel(parent=self.frmItem9)
        self.lblItem9.setMinimumSize(QtCore.QSize(220, 150))
        self.lblItem9.setPixmap(QtGui.QPixmap("images/7up.png"))
        self.lblItem9.setScaledContents(True)
        self.lblItem9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblItem9.setProperty("iconSize", QtCore.QSize(50, 70))
        self.lblItem9.setObjectName("lblItem9")
        self.verticalLayout_9.addWidget(self.lblItem9)
        self.hlayout_btns9 = QtWidgets.QHBoxLayout()
        self.hlayout_btns9.setContentsMargins(10, 10, 10, -10)
        self.hlayout_btns9.setObjectName("hlayout_btns9")
        self.btnAdd9 = QtWidgets.QPushButton(parent=self.frmItem9)
        self.btnAdd9.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd9.setStyleSheet("background-color:#4CAF50;color:white;")
        self.btnAdd9.setObjectName("btnAdd9")
        self.hlayout_btns9.addWidget(self.btnAdd9)
        self.btnMinus9 = QtWidgets.QPushButton(parent=self.frmItem9)
        self.btnMinus9.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMinus9.setStyleSheet("background-color:#E53935;color:white;")
        self.btnMinus9.setObjectName("btnMinus9")
        self.hlayout_btns9.addWidget(self.btnMinus9)
        self.verticalLayout_9.addLayout(self.hlayout_btns9)
        self.gridLayout_menu.addWidget(self.frmItem9, 2, 2, 1, 1)
        self.horizontalLayout_main.addWidget(self.frmMenu)
        self.frmCheckout = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmCheckout.setMinimumSize(QtCore.QSize(400, 0))
        self.frmCheckout.setStyleSheet("background-color: #f5f5f5;")
        self.frmCheckout.setObjectName("frmCheckout")
        self.verticalLayout_checkout = QtWidgets.QVBoxLayout(self.frmCheckout)
        self.verticalLayout_checkout.setObjectName("verticalLayout_checkout")
        self.lblCheckoutTitle = QtWidgets.QLabel(parent=self.frmCheckout)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblCheckoutTitle.setFont(font)
        self.lblCheckoutTitle.setStyleSheet("""
            QLabel#CheckoutTitle {
                background-color: #f5f5f5;
                border: 1px solid #dcdcdc;
                border-radius: 12px;
                padding: 4px 10px;
                font: bold 20pt \"Segoe UI\";
                color: #333;
        }
        """)
        self.lblCheckoutTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCheckoutTitle.setObjectName("lblCheckoutTitle")
        self.verticalLayout_checkout.addWidget(self.lblCheckoutTitle)
        self.lstItems = QtWidgets.QListWidget(parent=self.frmCheckout)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lstItems.setFont(font)
        self.lstItems.setObjectName("lstItems")
        self.lstItems.setStyleSheet("""
        QListWidget::item {
            color: black;
            font-size: 30px;
            padding: 10px;
        }
        """)
        self.verticalLayout_checkout.addWidget(self.lstItems)
        self.hlayout_total = QtWidgets.QHBoxLayout()
        self.hlayout_total.setObjectName("hlayout_total")
        self.lblTotal = QtWidgets.QLabel(parent=self.frmCheckout)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblTotal.setFont(font)
        self.lblTotal.setObjectName("lblTotal")
        self.hlayout_total.addWidget(self.lblTotal)
        self.btnCheckout = QtWidgets.QPushButton(parent=self.frmCheckout)
        self.btnCheckout.setStyleSheet("background-color:#FF9800;color:white;font-weight:bold;padding:6px 12px;border-radius:6px;")
        self.btnCheckout.setObjectName("btnCheckout")
        self.hlayout_total.addWidget(self.btnCheckout)
        self.hlayout_total.setStretch(0, 2)
        self.hlayout_total.setStretch(1, 1)
        self.verticalLayout_checkout.addLayout(self.hlayout_total)
        self.horizontalLayout_main.addWidget(self.frmCheckout)
        self.horizontalLayout_main.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fast Food Menu"))
        self.lblMenuTitle.setText(_translate("MainWindow", "Menu"))
        self.btnAdd1.setText(_translate("MainWindow", "+"))
        self.btnMinus1.setText(_translate("MainWindow", "-"))
        self.btnAdd2.setText(_translate("MainWindow", "+"))
        self.btnMinus2.setText(_translate("MainWindow", "-"))
        self.btnAdd3.setText(_translate("MainWindow", "+"))
        self.btnMinus3.setText(_translate("MainWindow", "-"))
        self.btnAdd4.setText(_translate("MainWindow", "+"))
        self.btnMinus4.setText(_translate("MainWindow", "-"))
        self.btnAdd5.setText(_translate("MainWindow", "+"))
        self.btnMinus5.setText(_translate("MainWindow", "-"))
        self.btnAdd6.setText(_translate("MainWindow", "+"))
        self.btnMinus6.setText(_translate("MainWindow", "-"))
        self.btnAdd7.setText(_translate("MainWindow", "+"))
        self.btnMinus7.setText(_translate("MainWindow", "-"))
        self.btnAdd8.setText(_translate("MainWindow", "+"))
        self.btnMinus8.setText(_translate("MainWindow", "-"))
        self.btnAdd9.setText(_translate("MainWindow", "+"))
        self.btnMinus9.setText(_translate("MainWindow", "-"))
        self.lblCheckoutTitle.setText(_translate("MainWindow", "Giỏ hàng"))
        self.lblTotal.setText(_translate("MainWindow", "Tổng tiền: 0đ"))
        self.btnCheckout.setText(_translate("MainWindow", "Thanh toán"))
